import  "bootstrap/dist/css/bootstrap.css"
import  "bootstrap/dist/css/bootstrap.min.css"
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { AOSInit } from '../components/Aos'
import { Inter } from "next/font/google";
import AddBootstrap from "..components/AddBootstrap";
import "animate.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSInit />
        <AddBootstrap/>
        {children}
      </body>
    </html>
  );
}
